[package]
name = "scenable"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
eyre = "0.6"
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
i18n-embed = { version = "0.12", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.5"
rust-embed = "5.9"
lazy_static = "1.4"
nom = "6"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
pretty_assertions = "0.7"
insta = "1.7"